services:
  chatbot:
    image: chatbot
    build: chatbot
    ports:
      - "5005:5005"
      - "5055:5055"
    environment:
      - DB_host=db
      - DB_user=root
      - DB_password=secret
      - DB_database=BalerionMySQL
      - SERVER=http://server:3000  
      - DB_port=3306
  frontend:
    image: frontend
    build: frontend
    ports:
      - "8080:8080" 
    environment:     
      - RASA=http://chatbot:5005/webhooks/rest/webhook
  server:
    image: server
    build: server
    ports:
      - "3000:3000"   
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=BalerionMySQL
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql    